# version: '3.8'

services:
  nginx:
    build: ./nginx
    image: nginx_i
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    build: ./wordpress
    image: wordpress_i
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - inception
    restart: on-failure

  mariadb:
    build: ./mariadb
    image: mariadb_i
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - inception
    # restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/mariadb

networks:
  inception:
    driver: bridge