# version: '3.8'

services:
  nginx:
    build: ./nginx
    image: nginx_i
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    build: ./wordpress
    image: wordpress_i
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  mariadb:
    build: ./mariadb
    image: mariadb_i
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/mariadb

networks:
  inception:
    driver: bridge